[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = ["database.js", "server.js", "sql-asm.js", "data/**"]
  external_node_modules = ["sql.js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
